name: CI_CD for my Python Application

on:
  push:
    branches:
    - main

jobs:
  running-python-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repo
      uses: actions/checkout@v3

    - name: Python environment setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Running Python Script
      run: python main.py
